CREATE  TABLE IF NOT EXISTS 'boatekiss' . 'Falecido' (
  'nome'  VARCHAR(100) NOT NULL COMMENT 'Nome do Falecido.',
  `idade` INT NOT NULL COMMENT 'idade do Falecido.',
 `sexo` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'M ou F.'
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
